In [1]:
import numpy as np

# Creating a basic array

In [7]:
a=np.array([4,5,6,7,8,9])

In [8]:
a

array([4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.ones(1)

array([1.])

In [12]:
np.empty(2)

array([1., 1.])

In [13]:
np.arange(3)

array([0, 1, 2])

In [14]:
np.arange(1,3,5)

array([1])

In [15]:
np.linspace(0, 8, num=4)

array([0.        , 2.66666667, 5.33333333, 8.        ])

In [16]:
x=np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

# Adding,removing, and sorting elements


In [17]:
arr=np.array([5,8,1,2,9,5,7,])

In [18]:
np.sort(arr)

array([1, 2, 5, 5, 7, 8, 9])

In [30]:
a=np.array([0,1,2,3])
b=np.array([4,5,6,7])

In [31]:
np.concatenate((a,b))

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
x=np.array([[0,1],[2,3]])
y=np.array([[4,5]])

In [33]:
np.concatenate((x,y), axis=0)

array([[0, 1],
       [2, 3],
       [4, 5]])

# Shape and size of an array

In [34]:
array_ex=np.array([[[3,4,5],
                   [6,7,8]],
                   
                  [[3,4,5],
                  [6,7,8]],
                   
                   [[3,4,5],
                   [6,7,8]]])

In [35]:
array_ex.ndim

3

In [36]:
array_ex.shape

(3, 2, 3)

In [37]:
array_ex.size

18

# Reshape an array

In [40]:
a=np.arange(8)

In [41]:
print(a)

[0 1 2 3 4 5 6 7]


In [45]:
b=a.reshape(4,2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


# Converting a 1D array into a 2D array(how to add a new axis to an array)

In [49]:
a=np.array([4,5,6,7,8,9])
a.shape

(6,)

In [50]:
a2=a[np.newaxis, :]
a2.shape

(1, 6)

In [51]:
row_vector= a[np.newaxis, :]
row_vector.shape

(1, 6)

In [52]:
col_vector=a[:,np.newaxis]
col_vector.shape

(6, 1)

In [53]:
a=np.array([4,5,6,7,8,9])
a.shape

(6,)

In [54]:
b=np.expand_dims(a,axis=1)
b.shape

(6, 1)

In [55]:
c=np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and Slicing

In [56]:
data=np.array([4,5,6])

In [57]:
data[1]

5

In [58]:
data[0:2]

array([4, 5])

In [59]:
data[1:]

array([5, 6])

In [62]:
data[-2:]

array([5, 6])

In [63]:
a=np.array([[0,1,2,3],[4,5,6,7],[7,8,9,0]])

In [64]:
print(a[a<5])

[0 1 2 3 4 0]


In [67]:
five_up=(a>=5)
print(a[five_up])

[5 6 7 7 8 9]


In [68]:
divisible_by_2=a[a%2==0]
print(divisible_by_2)

[0 2 4 6 8 0]


In [69]:
c=a[(a>2) & (a<11)]
print(c)

[3 4 5 6 7 7 8 9]


In [70]:
five_up=(a>5) | (a==5)
print(five_up)

[[False False False False]
 [False  True  True  True]
 [ True  True  True False]]


In [71]:
a=np.array([[0,1,2,3],[4,5,6,7],[7,8,9,0]])

In [72]:
b=np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0, 1, 2], dtype=int64), array([0, 1, 2, 3, 0, 3], dtype=int64))


In [73]:
list_of_coordinates=list(zip(b[0],b[1]))
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)
(1, 0)
(2, 3)


In [74]:
print(a[b])

[0 1 2 3 4 0]


In [77]:
not_there=np.nonzero(a==42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# Creating an array from existing data

In [78]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [79]:
arr1=a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [80]:
a1=np.array([[1,1],
            [2,2]])
a2=np.array([[3,3],
            [4,4]])

In [81]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [82]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [83]:
x=np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [84]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [85]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [86]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [87]:
b1=a[0, :]
b1

array([1, 2, 3, 4])

In [88]:
b1[0]=99
b1

array([99,  2,  3,  4])

In [89]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [90]:
b2=a.copy()

# Basic array operations

In [91]:
data=np.array([1,2])

In [92]:
ones=np.ones(2,dtype=int)

In [93]:
data+ones

array([2, 3])

In [94]:
data-ones

array([0, 1])

In [95]:
data*data

array([1, 4])

In [96]:
data / data

array([1., 1.])

In [97]:
a=np.array([4,5,6,7])

In [98]:
a.sum()

22

In [99]:
b=np.array([[2,2],[3,3]])

In [100]:
b.sum(axis=0)

array([5, 5])

In [101]:
b.sum(axis=1)

array([4, 6])

# Broadcasting

In [102]:
data=np.array([1.0, 2.0])
data*1.6

array([1.6, 3.2])

# Array operations

In [103]:
data.max()

2.0

In [104]:
data.min()

1.0

In [105]:
data.sum()

3.0

In [106]:
a=np.array([[0.456678423, 0.673838272, 0.32435356],
           [0.54646387, 0.01456579, 0.44561234],
           [0.45574648, 0.12345678, 0.76868689]])

In [107]:
a.sum()

3.809402405

In [108]:
a.min()

0.01456579

In [109]:
a.min(axis=0)

array([0.45574648, 0.01456579, 0.32435356])

# Creating matrices

In [110]:
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [111]:
data[0,1]

2

In [112]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [113]:
data[0:2, 0]

array([1, 3])

In [114]:
data.max()

6

In [115]:
data.min()

1

In [116]:
data.sum()

21

In [117]:
data.max(axis=0)

array([5, 6])

In [118]:
data.max(axis=1)

array([2, 4, 6])

In [119]:
data=np.array([[1,2],[3,4]])
ones=np.array([[1,1],[1,1]])
data+ones

array([[2, 3],
       [4, 5]])

In [120]:
data=np.array([[1,2],[3,4],[5,6]])
ones_row=np.array([[1,1]])
data+ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [121]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [122]:
np.ones(3)

array([1., 1., 1.])

In [123]:
np.zeros(3)

array([0., 0., 0.])

In [124]:
rng=np.random.default_rng(0)

In [125]:
rng.random(3)

array([0.63696169, 0.26978671, 0.04097352])

In [126]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [127]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [128]:
rng.random((3,2))

array([[0.01652764, 0.81327024],
       [0.91275558, 0.60663578],
       [0.72949656, 0.54362499]])

# Generating random numbers

In [129]:
rng.integers(5, size=(2,4))

array([[2, 4, 1, 4],
       [3, 0, 1, 4]], dtype=int64)

# How to get unique items and counts

In [130]:
a=np.array([11,11,12,13,14,15,16,17,12,13,11,14,18,19,20])

In [131]:
unique_values=np.unique(a)

In [132]:
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [133]:
unique_values, indices_list=np.unique(a,return_index=True)

In [134]:
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [135]:
unique_values,occurence_count=np.unique(a, return_counts=True)

In [136]:
print(occurence_count)

[3 2 2 2 1 1 1 1 1 1]


In [137]:
a_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[1,2,3,4]])

In [138]:
unique_values=np.unique(a_2d)

In [139]:
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [140]:
unique_rows=np.unique(a_2d,axis=0)

In [141]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [143]:
unique_rows,indices,occurence_count=np.unique(a_2d,axis=0,return_counts=True,return_index=True)

In [144]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [145]:
print(indices)

[0 1 2]


In [146]:
print(occurence_count)

[2 1 1]


# Transposing and reshaping a matrix

In [147]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [149]:
arr=np.arange(6).reshape((2,3))

In [150]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [151]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [152]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

# How to reverse an array

In [153]:
arr=np.array([1,2,3,4,5,6,7,8])

In [154]:
reversed_arr=np.flip(arr)

In [155]:
print('Reversed Array: ',reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [156]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [157]:
reversed_arr=np.flip(arr_2d)

In [158]:
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [159]:
reversed_arr_rows=np.flip(arr_2d,axis=0)

In [160]:
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [161]:
reversed_arr_columns=np.flip(arr_2d,axis=1)

In [162]:
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [163]:
arr_2d[1]=np.flip(arr_2d[1])

In [164]:
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [165]:
arr_2d[:,1]=np.flip(arr_2d[:,1])

In [166]:
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


# Reshaping and flattening multidimensional arrays

In [167]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [168]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [169]:
a1=x.flatten()

In [170]:
a1[0]=99

In [171]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [172]:
print(a1)

[99  2  3  4  5  6  7  8  9 10 11 12]


In [173]:
a2=x.ravel()

In [174]:
a2[0]=98

In [175]:
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [176]:
print(a2)

[98  2  3  4  5  6  7  8  9 10 11 12]
