# welcome to numpy!

# Numpy code example

In [ ]:
import numpy as np

In [4]:
npdata=np.arange(1,21,3)
npdata

array([ 1,  4,  7, 10, 13, 16, 19])

#  Initialize Numpy arrays from python lists

In [6]:
mypythonlist=[1,9,8,3]
numpy_array_from_list=np.array(mypythonlist)
numpy_array_from_list

array([1, 9, 8, 3])

# Mathematical operations on an array (+,-,*,/)

In [7]:
numpy_array_from_list+10

array([11, 19, 18, 13])

# Shape of array using dtype

In [8]:
import numpy as np
a=np.array([1,2,3])
print(a.shape)
print(a.dtype)

(3,)
int32


# create an array with decimal

In [9]:
#### Different type
b=np.array([1.1,2.0,3.2])
print(b.dtype)

float64


# 2 Dimension array

In [10]:
### 2 Dimension
c=np.array([(1,2,3),(4,5,6)])
print(c.shape)

(2, 3)


# 3 Dimension array

In [13]:
### 3 Dimension
d=np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])
print(d.shape)

(2, 2, 3)


# How to create a basic array(using np.array(),np.zeros(),np.ones(),np.empty(),np.arange(),np.linspace(),np.reshape(),np.flatten(),np.hstack(),np.vstack(),)

In [16]:
import numpy as np
a=np.array([7,8,9])
np.array([7,8,9])

array([7, 8, 9])

In [18]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
import numpy as np
np.ones ((1,2,3),
        dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [20]:
import numpy as np
e=np.array([(1,2,3),
           (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
import numpy as np
np.empty(2)


array([1.12723336e-311, 1.46417710e-312])

In [23]:
import numpy as np
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
import numpy as np
np.linspace(1.0,5.0,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [25]:
import numpy as np
e.flatten()

array([1, 2, 3, 4, 5, 6])

In [26]:
## Horizontal Stack
import numpy as np
f=np.array([1,2,3])
g=np.array([4,5,6])
print('Horizontal Append:',
     np.hstack((f,g)))

Horizontal Append: [1 2 3 4 5 6]


In [27]:
## Veritcal stack
import numpy as np
f=np.array([1,2,3])
g=np.array([4,5,6])
print('Vertical Append:',np.vstack((f,g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


# Generate Random Numbers using numpy

In [28]:
## Generate random number from normal distribution
normal_array=np.random.normal(5,0.5,10)
print(normal_array)

[3.9488166  5.2520673  4.67930442 5.66271492 4.42764416 4.99328869
 5.23681114 4.94137085 5.05125951 5.1502391 ]


# Numpy Asarray function

In [29]:
import numpy as np
A=np.matrix(np.ones((4,4)))
np.array(A)[2]=2
print(A)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# LogSpace numpy function in python

In [31]:
import numpy as np
np.logspace(3.0,4.0,num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

# Indexing and slicing in python

In [32]:
## Slice
import numpy as np
e=np.array([(1,2,3),
            (4,5,6)])
print(e)

[[1 2 3]
 [4 5 6]]


In [33]:
## First column
print('First row:',e[0])
## second col
print('second row :',e[1])

First row: [1 2 3]
second row : [4 5 6]


# Statistical functions in python(min,max,mean,median,standard deviation)

In [34]:
import numpy as np
normal_array=np.random.normal(5,0.5,10)
print(normal_array)

[5.06898056 5.16457537 5.38608617 4.1592823  4.96049549 5.42202417
 5.11011812 4.91891609 4.49381712 5.20188463]


In [36]:
### min
print(np.min(normal_array))
### max
print(np.max(normal_array))
### mean
print(np.mean(normal_array))
### median
print(np.median(normal_array))
### sd
print(np.std(normal_array))

4.159282302749957
5.422024166592277
4.988618003605237
5.0895493427641965
0.37172042821737517


# numpy dot products

In [37]:
## linear algebra
### dot product: product of two arrays
f=np.array([1,2])
g=np.array([4,5])
### 1*4+2*5
np.dot(f,g)

14

# Matrix multiplication in python

In [38]:
### matmul:matruc product of two arrays
h=[[1,2],[3,4]]
i=[[5,6],[7,8]]
### 1*5+2*7=19
np.matmul(h,i)

array([[19, 22],
       [43, 50]])

# Adding,removing,sorting elements

In [42]:
import numpy
a=numpy.array([1,2,3])
newarray=numpy.append(a,[10,11,12])
print(newarray)

[ 1  2  3 10 11 12]


In [43]:
import numpy
a=numpy.array([1,2,3])
newarray=numpy.delete(a,1,axis=0)
print(newarray)

[1 3]


In [44]:
import numpy
a=numpy.array([16,3,2,6,8,10,1])
print("sorted array=",numpy.sort(a))

sorted array= [ 1  2  3  6  8 10 16]


# Reverse an array

In [45]:
arr=np.array([9,8,7,6,5,4,3,2,1])
reversed_arr=np.flip(arr)
print('reversed array:',reversed_arr)

reversed array: [1 2 3 4 5 6 7 8 9]


# save and load numpy objects

In [47]:
a=np.array([7,8,9,4])
np.save('filename',a)
b=np.load('filename.npy')
print(b)

[7 8 9 4]
