In [1]:
import numpy as np


In [2]:
farray = np.array([1, 3, 5 ,7])

In [3]:
farray

array([1, 3, 5, 7])

In [4]:
print(farray[0])

1


In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.ones(4)

array([1., 1., 1., 1.])

In [7]:
np.empty(2)

array([ 8.97874271e+094, -2.01353784e-298])

In [8]:
np.arange(4)

array([0, 1, 2, 3])

In [9]:
np.linspace(1,4, num = 10)

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [10]:
np.ones(2,dtype = np.int64)

array([1, 1], dtype=int64)

adding,romoving and sorting



In [11]:
z=np.array([4,6,10,11,10,5])

In [12]:
np.sort(z)

array([ 4,  5,  6, 10, 10, 11])

In [13]:
np.argsort(z)

array([0, 5, 1, 2, 4, 3], dtype=int64)

In [14]:
np.partition(z, 1)


array([ 4,  5, 10, 11, 10,  6])

In [15]:
y=np.array([5,10,13,16,17])
np.concatenate((z,y))

array([ 4,  6, 10, 11, 10,  5,  5, 10, 13, 16, 17])

In [16]:
x=np.array([[1,2],[3,6]])
m=np.array([[5,6]])

In [17]:
j=np.concatenate((x, m),axis =0)


In [18]:
j

array([[1, 2],
       [3, 6],
       [5, 6]])

In [19]:
j.ndim

2

In [20]:
z = np.arange(6)
print(z)

[0 1 2 3 4 5]


In [21]:
j.shape


(3, 2)

In [22]:
j.size


6

In [23]:
z.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [24]:
m=z[np.newaxis, :]
m.shape

(1, 6)

In [25]:
g=z[:,np.newaxis]
g.shape

(6, 1)

In [26]:


z[1]



1

In [27]:
z[0:2]


array([0, 1])

In [28]:
z[1:]



array([1, 2, 3, 4, 5])

In [29]:
z[-2:]

array([4, 5])

In [30]:
z[2:5]


array([2, 3, 4])

In [31]:
b = np.array([[14 , 2, 3, 4], [5, 619, 7, 8], [19, 10, 11, 12]])


In [32]:
(b[b < 5])


array([2, 3, 4])

In [33]:
m=(b >= 5)
print(b[m])


[ 14   5 619   7   8  19  10  11  12]


In [34]:
b[b%2==0]

array([14,  2,  4,  8, 10, 12])

In [35]:
b[(b > 3) & (b < 11)]


array([ 4,  5,  7,  8, 10])

In [36]:
g = (b > 5) | (b == 5)


In [37]:
print(g)

[[ True False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [38]:
c=np.nonzero(b < 5)

In [39]:
print(b[c])

[2 3 4]


In [40]:
myarray = np.array([1,14,2,13,4,15,6,8,9,10])


In [41]:
myarray2=myarray[4:6]

In [42]:
myarray2

array([ 4, 15])

In [43]:
z1 = np.array([[1, 1],
               [2, 2]])

z2 = np.array([[3,2 ],
               [4, 4]])


In [44]:
np.vstack((z1,z2))

array([[1, 1],
       [2, 2],
       [3, 2],
       [4, 4]])

In [45]:
np.hstack((z1,z2))


array([[1, 1, 3, 2],
       [2, 2, 4, 4]])

In [46]:
 new= np.arange(2, 26).reshape(2, 12)
    

In [47]:
np.hsplit(new, (4, 4))

[array([[ 2,  3,  4,  5],
        [14, 15, 16, 17]]),
 array([], shape=(2, 0), dtype=int32),
 array([[ 6,  7,  8,  9, 10, 11, 12, 13],
        [18, 19, 20, 21, 22, 23, 24, 25]])]

In [48]:
np.hsplit(new, 3)

[array([[ 2,  3,  4,  5],
        [14, 15, 16, 17]]),
 array([[ 6,  7,  8,  9],
        [18, 19, 20, 21]]),
 array([[10, 11, 12, 13],
        [22, 23, 24, 25]])]

In [49]:
z=b[1, :]

In [50]:
z


array([  5, 619,   7,   8])

In [51]:
z[0]= 100


In [52]:
z

array([100, 619,   7,   8])

In [53]:
b

array([[ 14,   2,   3,   4],
       [100, 619,   7,   8],
       [ 19,  10,  11,  12]])

In [54]:
b2 = b.copy()


In [55]:
b2


array([[ 14,   2,   3,   4],
       [100, 619,   7,   8],
       [ 19,  10,  11,  12]])

In [56]:
data = np.array([5, 2])
ones = np.ones(2, dtype=int)
data + ones

array([6, 3])

In [57]:
d=[1,3,4]
f=[6,7,8]

In [58]:
d+f

[1, 3, 4, 6, 7, 8]

In [59]:
np.array(d)+np.array(f)
#you can also perform subtrationa,multiplication and division

array([ 7, 10, 12])

In [61]:
np.array(d).sum()#adds all the elements in an array, you can also do it by assigning it to a variable

8

In [62]:
b.sum()

809

In [70]:
data = np.array([2, 2])
ones = np.ones(2, dtype=int)
data + ones

array([3, 3])

In [64]:
b.sum(axis=0)#to sum over the axis

array([133, 631,  21,  24])

In [65]:
b

array([[ 14,   2,   3,   4],
       [100, 619,   7,   8],
       [ 19,  10,  11,  12]])

In [66]:
b*1.6


array([[ 22.4,   3.2,   4.8,   6.4],
       [160. , 990.4,  11.2,  12.8],
       [ 30.4,  16. ,  17.6,  19.2]])

In [68]:
b.max()

619

In [69]:
b.min()

2

In [71]:
ata = np.array([[1, 2], [3, 4], [5, 6]])
ata


array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
ata[0, 1]


2

In [74]:
ata[1:3]


array([[3, 4],
       [5, 6]])

In [76]:
ata[0:2, 0]

array([1, 3])

In [77]:
ata[0:2,]

array([[1, 2],
       [3, 4]])

In [78]:
ata[0:2]

array([[1, 2],
       [3, 4]])

In [79]:
ata.max(axis=0)

array([5, 6])

In [80]:
ata.min(axis=1)



array([1, 3, 5])

In [81]:
ata = np.array([[1, 2], [3, 4], [5, 6]])
row = np.array([[1, 1]])

In [82]:
ata+row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [87]:
np.ones((4, 3, 2),dtype=int)


array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])