In [1]:
import numpy as np

# How to create a basic array

In [2]:
a=np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
np.zeros(1)

array([0.])

In [5]:
np.zeros(2)

array([0., 0.])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.ones(2)

array([1., 1.])

In [8]:
np.empty(4)

array([2.12199579e-314, 0.00000000e+000, 7.94457559e-321, 2.86469432e-312])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,12,3)

array([3, 6, 9])

In [11]:
np.linspace(1,12,4)

array([ 1.        ,  4.66666667,  8.33333333, 12.        ])

In [12]:
x=np.ones(4, dtype=np.int32)

In [13]:
x

array([1, 1, 1, 1])

# Adding,removing and sorting elements

In [14]:
ar=np.array([1,2,5,6,7,4,9])

In [15]:
ar

array([1, 2, 5, 6, 7, 4, 9])

In [16]:
np.sort(ar)

array([1, 2, 4, 5, 6, 7, 9])

In [17]:
np.lexsort(ar)

0

In [18]:
np.argsort(ar)

array([0, 1, 5, 2, 3, 4, 6], dtype=int64)

In [19]:
np.partition(ar, 6)

array([4, 1, 5, 2, 6, 7, 9])

In [20]:
np.searchsorted(ar, 4)

2

In [21]:
a=np.array([1,2,3,4])
b=np.array([2,4,6,7])

In [22]:
np.concatenate((a,b))

array([1, 2, 3, 4, 2, 4, 6, 7])

In [23]:
x=np.array([[2,4],[3,5]])
y=np.array([[5,7],[6,5]])

In [24]:
np.concatenate((x,y))

array([[2, 4],
       [3, 5],
       [5, 7],
       [6, 5]])

In [25]:
np.concatenate((x), axis=0)

array([2, 4, 3, 5])

# shape and size of an array

In [26]:
ar=np.array([[1,2,4],[5,4,7],[7,8,0]])

In [27]:
ar

array([[1, 2, 4],
       [5, 4, 7],
       [7, 8, 0]])

In [28]:
ar.ndim

2

In [29]:
ar.size

9

In [30]:
ar.shape

(3, 3)

# reshape an array

In [31]:
a=np.arange(20)

In [32]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
a.reshape(10,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [34]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

# Covert 1D array into a 2D array(add new axis to an array)

In [35]:
a=np.array([3,6,8,9])

In [36]:
a.shape

(4,)

In [37]:
a2=a[np.newaxis, :]

In [38]:
a2.shape

(1, 4)

In [39]:
row_vector=a[np.newaxis, :]

In [40]:
row_vector.shape

(1, 4)

In [41]:
col_vector=a[:, np.newaxis]

In [42]:
col_vector.shape

(4, 1)

# changing an element in an array

In [43]:
a[0]=4

In [44]:
a

array([4, 6, 8, 9])

# indexing and slicing

In [45]:
ind=np.array([5,6,7,8])

In [46]:
ind[3]

8

In [47]:
ind[0:2]

array([5, 6])

In [48]:
ind[0:1]

array([5])

In [49]:
ind[-2:]

array([7, 8])

In [50]:
a=np.array([[1,3,4,5],[4,5,6,2],[15,6,18,9],[9,11,5,8]])

In [51]:
a

array([[ 1,  3,  4,  5],
       [ 4,  5,  6,  2],
       [15,  6, 18,  9],
       [ 9, 11,  5,  8]])

In [52]:
print(a[a<11])

[1 3 4 5 4 5 6 2 6 9 9 5 8]


In [53]:
aa=(a>=11)

In [54]:
print(a[aa])

[15 18 11]


In [55]:
np.sort(a)

array([[ 1,  3,  4,  5],
       [ 2,  4,  5,  6],
       [ 6,  9, 15, 18],
       [ 5,  8,  9, 11]])

In [56]:
div=a[a%3==0]

In [57]:
print(div)

[ 3  6 15  6 18  9  9]


In [58]:
c=a[(a>3) & (a<11)]

In [59]:
print(c)

[4 5 4 5 6 6 9 9 5 8]


In [60]:
bb=(a>6) | (a==6)

In [61]:
print(bb)

[[False False False False]
 [False False  True False]
 [ True  True  True  True]
 [ True  True False  True]]


In [62]:
a

array([[ 1,  3,  4,  5],
       [ 4,  5,  6,  2],
       [15,  6, 18,  9],
       [ 9, 11,  5,  8]])

In [63]:
b=np.nonzero(a<5)

In [64]:
print(b)

(array([0, 0, 0, 1, 1], dtype=int64), array([0, 1, 2, 0, 3], dtype=int64))


In [65]:
list_of_coordinates=list(zip(b[0],b[1]))

In [66]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 3)


In [67]:
print(a[b])

[1 3 4 4 2]


In [68]:
not_there=np.nonzero(a==42)

In [69]:
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# create an array from existing data

In [70]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [71]:
ar1=a[3:8]

In [72]:
ar1

array([4, 5, 6, 7, 8])

In [73]:
a1=np.array([[1,1],
           [2,2]])
a2=np.array([[3,3],[4,4]])

In [74]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [75]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [76]:
x=np.arange(1,25).reshape(2,12)

In [77]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [78]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [79]:
np.hsplit(x,(3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

# Basic array operations

In [80]:
ar=np.array([1,2,3,4,5])

In [81]:
ones=np.ones(5,dtype=int)

In [82]:
ar+ones

array([2, 3, 4, 5, 6])

In [83]:
ar-ones

array([0, 1, 2, 3, 4])

In [84]:
ar*ar

array([ 1,  4,  9, 16, 25])

In [85]:
ar/ar

array([1., 1., 1., 1., 1.])

In [86]:
ar.sum()

15

In [87]:
b=np.array([[1,2,3],[4,5,2],[6,7,3]])


In [88]:
b

array([[1, 2, 3],
       [4, 5, 2],
       [6, 7, 3]])

In [89]:
b.sum(axis=0)

array([11, 14,  8])

In [90]:
b.sum(axis=1)

array([ 6, 11, 16])

# Brodcasting

In [91]:
dd=np.array([1.0,2.0,3.0,4.0])

In [92]:
dd*2.2

array([2.2, 4.4, 6.6, 8.8])

# More useful array oprerations

In [93]:
dd.max()

4.0

In [94]:
dd.min()

1.0

In [95]:
dd.sum()

10.0

# Creating matrices

In [96]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [97]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
ar[0,1]

2

In [99]:
ar[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [100]:
ar[0:2, 0]

array([1, 4])

In [101]:
ar.max(axis=0)

array([7, 8, 9])

In [102]:
ar.min(axis=1)

array([1, 4, 7])

In [103]:
ar.sum()

45

In [104]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
a=np.array([[1,2,4],[4,3,6],[5,8,9]])

In [106]:
a

array([[1, 2, 4],
       [4, 3, 6],
       [5, 8, 9]])

In [107]:
ar+a

array([[ 2,  4,  7],
       [ 8,  8, 12],
       [12, 16, 18]])

In [108]:
ar*a

array([[ 1,  4, 12],
       [16, 15, 36],
       [35, 64, 81]])

In [109]:
ar-a

array([[ 0,  0, -1],
       [ 0,  2,  0],
       [ 2,  0,  0]])

In [110]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [111]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [112]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [113]:
rng=np.random.default_rng(0)

In [114]:
rng.random(4)

array([0.63696169, 0.26978671, 0.04097352, 0.01652764])

In [115]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [116]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [117]:
rng.random((4,2))

array([[0.81327024, 0.91275558],
       [0.60663578, 0.72949656],
       [0.54362499, 0.93507242],
       [0.81585355, 0.0027385 ]])

In [118]:
rng.integers(5, size=(2,4))

array([[1, 4, 2, 0],
       [3, 3, 4, 0]], dtype=int64)

# getting unique items and counts

In [119]:
a=np.array([1,1,2,2,3,4,5,6,5,7,8,6,9])

In [120]:
a

array([1, 1, 2, 2, 3, 4, 5, 6, 5, 7, 8, 6, 9])

In [121]:
uni=np.unique(a)

In [122]:
print(uni)

[1 2 3 4 5 6 7 8 9]


In [123]:
uni,ind_list=np.unique(a, return_index=True)

In [124]:
print(ind_list)

[ 0  2  4  5  6  7  9 10 12]


In [125]:
uni,occ_count=np.unique(a,return_counts=True)

In [126]:
print(occ_count)

[2 2 1 1 2 2 1 1 1]


In [127]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [128]:
uni=np.unique(ar)

In [129]:
print(uni)

[1 2 3 4 5 6 7 8 9]


In [130]:
uni_rows=np.unique(ar,axis=0)

In [131]:
print(uni_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [132]:
uni_rows,ind,occ_count=np.unique(ar,axis=0,return_counts=True,return_index=True)

In [133]:
print(uni_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [134]:
print(ind)

[0 1 2]


In [135]:
print(occ_count)

[1 1 1]


# Transposing and reshaping

In [136]:
ar=np.array([[1,2,3],[6,7,8],[2,3,6]])

In [137]:
ar

array([[1, 2, 3],
       [6, 7, 8],
       [2, 3, 6]])

In [138]:
ar.T

array([[1, 6, 2],
       [2, 7, 3],
       [3, 8, 6]])

In [139]:
dd=np.array([[1,2],[3,4],[5,6]])

In [140]:
dd

array([[1, 2],
       [3, 4],
       [5, 6]])

In [141]:
dd.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
dd.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [143]:
ar.transpose()

array([[1, 6, 2],
       [2, 7, 3],
       [3, 8, 6]])

# reverse an array

In [144]:
arr=np.array([1,2,3,4,5,6,7])

In [145]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [146]:
reversed_arr=np.flip(arr)

In [147]:
print('Reversed Array: ',reversed_arr)

Reversed Array:  [7 6 5 4 3 2 1]


In [148]:
ar

array([[1, 2, 3],
       [6, 7, 8],
       [2, 3, 6]])

In [149]:
reversed_arr=np.flip(ar)

In [150]:
print(reversed_arr)

[[6 3 2]
 [8 7 6]
 [3 2 1]]


In [151]:
reversed_arr_rows=np.flip(ar,axis=0)

In [152]:
print(reversed_arr_rows)

[[2 3 6]
 [6 7 8]
 [1 2 3]]


In [153]:
reversed_arr_columns=np.flip(ar,axis=1)

In [154]:
print(reversed_arr_columns)

[[3 2 1]
 [8 7 6]
 [6 3 2]]


In [155]:
ar[1]=np.flip(ar[1])

In [156]:
print(ar)

[[1 2 3]
 [8 7 6]
 [2 3 6]]


In [157]:
ar[:,1]=np.flip(ar[:,1])

In [158]:
print(ar)

[[1 3 3]
 [8 7 6]
 [2 2 6]]


# reshaping and flattening multidimensional arrays

In [159]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [160]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
a1=x.flatten()

In [165]:
a1[0]=85

In [166]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [167]:
print(a1)

[85  2  3  4  5  6  7  8  9]


In [168]:
a2=x.ravel()

In [169]:
a2[0]=70

In [170]:
print(x)

[[70  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [171]:
print(a2)

[70  2  3  4  5  6  7  8  9]
